// <auto-generated />
using System;
using FinancialDashboard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialDashboard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FinancialDashboard.API.Models.AlertHistory", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int?>("AlertId").HasColumnType("INTEGER");
                b.Property<string>("AlertType").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Notes").HasColumnType("TEXT");
                b.Property<decimal>("PercentChange").HasColumnType("TEXT");
                b.Property<decimal>("PriceAtTrigger").HasColumnType("TEXT");
                b.Property<string>("Symbol").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("TriggeredAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("AlertHistories");
            });

            modelBuilder.Entity("FinancialDashboard.API.Models.PriceAlert", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<DateTime?>("LastTriggeredAt").HasColumnType("TEXT");
                b.Property<string>("Symbol").IsRequired().HasColumnType("TEXT");
                b.Property<decimal>("ThresholdPercent").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("PriceAlerts");
            });

            modelBuilder.Entity("FinancialDashboard.API.Models.UserSettings", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<bool>("DailyBriefEnabled").HasColumnType("INTEGER");
                b.Property<string>("DailyBriefTime").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                b.Property<decimal>("VolatilityThreshold").HasColumnType("TEXT");
                b.Property<bool>("WeeklyReportEnabled").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.ToTable("UserSettings");
                b.HasData(new { Id = 1, DailyBriefEnabled = true, DailyBriefTime = "08:00", Email = "", VolatilityThreshold = 3.0m, WeeklyReportEnabled = true });
            });

            modelBuilder.Entity("FinancialDashboard.API.Models.WatchlistItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("AddedAt").HasColumnType("TEXT");
                b.Property<string>("CompanyName").HasColumnType("TEXT");
                b.Property<decimal?>("LastKnownPrice").HasColumnType("TEXT");
                b.Property<decimal?>("LastPercentChange").HasColumnType("TEXT");
                b.Property<DateTime?>("LastPriceUpdatedAt").HasColumnType("TEXT");
                b.Property<decimal?>("PreviousClose").HasColumnType("TEXT");
                b.Property<string>("Symbol").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("WatchlistItems");
            });
#pragma warning restore 612, 618
        }
    }
}
